[build]
command = "npm run inject-graphics && cp -r custom-graphics/buildings/village apps/web/public/graphic-packs/default/buildings/village && mkdir -p apps/web/public/graphic-packs/default/backgrounds && cp custom-graphics/backgrounds/village-*.jpg apps/web/public/graphic-packs/default/backgrounds/ && turbo run build"
publish = "apps/web/build/client"
image = "ubuntu-24.04"

# build envs
[build.environment]
NODE_VERSION = "24.12.0"

# branch-deploy
[context.branch-deploy]
command = "npm run inject-graphics && turbo run build:dev"

# deploy-preview
[context.deploy-preview]
command = "npm run inject-graphics && turbo run build:dev"
