import { Link } from 'react-router';
import type { BuildingField as BuildingFieldType } from '@pillage-first/types/models/building-field';

type EmptyBuildingFieldProps = {
  buildingFieldId: BuildingFieldType['id'];
};

// A staked out building site, generated by scripts/generate-village-scene.ts
const emptyBuildingFieldClassName =
  'block w-12 lg:w-20 h-8 lg:h-12 bg-contain bg-center bg-no-repeat rounded-full hover:brightness-115 hover:drop-shadow-[0_0_6px_rgba(255,236,170,0.9)] transition-[filter] focus:outline-hidden focus-visible:ring-2 focus-visible:ring-black/80 dark:focus-visible:ring-ring cursor-pointer';

const emptyBuildingFieldStyle = {
  backgroundImage: 'url(/village-scene/building-site.webp)',
};

export const EmptyBuildingField = ({
  buildingFieldId,
}: EmptyBuildingFieldProps) => {
  return (
    <Link
      to={`${buildingFieldId}`}
      relative="route"
      data-building-field-id={buildingFieldId}
      className={emptyBuildingFieldClassName}
      style={emptyBuildingFieldStyle}
    />
  );
};
