import type { Building } from '@pillage-first/types/models/building';
import type { BuildingField } from '@pillage-first/types/models/building-field';

// Images are generated by scripts/generate-village-scene.ts and
// scripts/generate-resource-fields.ts
type WallStyle = 'stone' | 'palisade' | 'earth';

const wallStyleByBuildingId = new Map<Building['id'], WallStyle>([
  ['ROMAN_WALL', 'stone'],
  ['EGYPTIAN_WALL', 'stone'],
  ['SPARTAN_WALL', 'stone'],
  ['NATAR_WALL', 'stone'],
  ['GAUL_WALL', 'palisade'],
  ['HUN_WALL', 'palisade'],
  ['TEUTONIC_WALL', 'earth'],
]);

// Soften the edges so the scene blends into the page background
const sceneMask =
  'radial-gradient(ellipse 50% 50% at 50% 50%, #000 78%, transparent 100%)';

type VillageSceneProps = {
  wallField: BuildingField | null;
};

export const VillageScene = ({ wallField }: VillageSceneProps) => {
  const wallStyle =
    wallField && wallField.level > 0
      ? wallStyleByBuildingId.get(wallField.buildingId)
      : undefined;

  return (
    <div
      aria-hidden
      className="absolute inset-0 pointer-events-none select-none bg-cover bg-center"
      style={{
        backgroundImage: 'url(/village-scene/village.webp)',
        maskImage: sceneMask,
        WebkitMaskImage: sceneMask,
      }}
    >
      {wallStyle && (
        <img
          src={`/village-scene/wall-${wallStyle}.webp`}
          alt=""
          className="absolute inset-0 size-full"
          draggable={false}
        />
      )}
    </div>
  );
};

const resourceFieldTypeByBuildingId = new Map<Building['id'], string>([
  ['WOODCUTTER', 'wood'],
  ['CLAY_PIT', 'clay'],
  ['IRON_MINE', 'iron'],
  ['WHEAT_FIELD', 'wheat'],
]);

// Fields look more developed at levels 1, 5 and 10
const getResourceFieldStage = (level: number) => {
  if (level >= 10) {
    return 3;
  }

  if (level >= 5) {
    return 2;
  }

  return level >= 1 ? 1 : 0;
};

export const getResourceFieldImage = (
  buildingId: Building['id'],
  level: number,
) => {
  const type = resourceFieldTypeByBuildingId.get(buildingId) ?? 'wheat';
  return `/resource-fields/${type}-${getResourceFieldStage(level)}.webp`;
};

export const ResourceFieldsScene = () => {
  return (
    <div
      aria-hidden
      className="absolute inset-0 pointer-events-none select-none bg-cover bg-center"
      style={{
        backgroundImage: 'url(/resource-fields/background.webp)',
        maskImage: sceneMask,
        WebkitMaskImage: sceneMask,
      }}
    />
  );
};
